name: Build and Publish Docker Image to GHCR

on:
  schedule:
    # Schedule the workflow to run daily at midnight UTC.
    - cron: '0 0 * * *'
  workflow_dispatch:
  registry_package:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get base image version
        id: get_version
        run: |
          echo "Fetching the base image version..."
          BASE_IMAGE_VERSION=$(curl --silent https://registry.hub.docker.com/v2/repositories/codercom/code-server/tags/latest | jq -r '.name')
          echo "Base image version: $BASE_IMAGE_VERSION"
          echo "version=$BASE_IMAGE_VERSION" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry (GHCR)
        run: |
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/code-server:${{ steps.get_version.outputs.version }}
          echo "Building Docker image with base image version ${{ steps.get_version.outputs.version }}..."
          docker build --build-arg BASE_IMAGE_VERSION=${{ steps.get_version.outputs.version }} -t $IMAGE_NAME .

      - name: Push Docker image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/code-server:${{ steps.get_version.outputs.version }}
          echo "Pushing Docker image $IMAGE_NAME to GHCR..."
          docker push $IMAGE_NAME