name: Build and Publish Docker Image to GHCR

on:
  schedule:
    # Schedule the workflow to run daily at midnight UTC.
    - cron: '0 0 * * *'
  workflow_dispatch:
  registry_package:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull the base image
        run: docker pull codercom/code-server:latest

      - name: Extract code-server version from the base image
        id: get_version
        run: |
          echo "Extracting the actual code-server version from the base image..."
          VERSION=$(docker run --rm codercom/code-server:latest code-server --version | head -n 1 | awk '{print $1}')
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry (GHCR)
        run: |
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/code-server:${{ steps.get_version.outputs.version }}
          echo "Building Docker image with base image version ${{ steps.get_version.outputs.version }}..."
          docker build -t $IMAGE_NAME .
          # Also create a latest tag
          docker tag $IMAGE_NAME ghcr.io/${{ github.repository_owner }}/code-server:latest

      - name: Push Docker image to GHCR
        run: |
          # Push versioned tag
          echo "Pushing Docker image with version ${{ steps.get_version.outputs.version }} to GHCR..."
          docker push ghcr.io/${{ github.repository_owner }}/code-server:${{ steps.get_version.outputs.version }}
          # Push latest tag
          echo "Pushing Docker image with tag latest to GHCR..."
          docker push ghcr.io/${{ github.repository_owner }}/code-server:latest