name: Build and Publish Docker Image to GHCR

on:
  schedule:
    # Schedule the workflow to run daily at midnight UTC.
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry (GHCR)
        run: |
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/code-server:latest
          echo "Building and pushing Docker image $IMAGE_NAME for multiple architectures..."
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME --push .
